language: cpp

services:
  - docker

matrix:
  include:
    - os: linux
      dist: xenial
      env: $DOCKER_IMAGE=ubuntu:18.04
    - os: linux
      dist: xenial
      env: $DOCKER_IMAGE=ubuntu:16.04
    - os: osx

before_install:
  - ./.cicd/before_install.sh

script: echo "ohai"
